### ISSUE TITLE
PLSSSSSSSSSSSS

### ISSUE THREAD

**Issue by Lym0nade** [w0bm/w0bm.com#237]
```
   a {
transition: color 0.1s linear;
-webkit-transition: 0.1s;
-moz-transition: 0.1s;
-o-transition: 0.1s;
}
```

**Comment by belst** [comment]
why no pull request?

**Comment by Flummi** [comment]
pr or nothing will happen :P

**Comment by jkhsjdhjs** [comment]
why is it needed?

**Comment by GottZ** [comment]
needs more animation

**Comment by jkhsjdhjs** [comment]
needs more reaction @invalid-email-address

**Comment by sirx** [comment]
reviewed und getestet und für ziemlich unnötig befunden, das bringt ja mal rein gar nichts, wtf?

Ich suggestiere fürs nächste mal eine ausführliche Beschreibung + was es tut wenn du irgendwas vorschlägst, hab das im CSS Editor ausprobiert und es sieht 1 zu 1 gleich aus.

**Comment by jkhsjdhjs** [comment]
> Ich suggestiere fürs nächste mal eine ausführliche Beschreibung

this pls

**Comment by Lym0nade** [comment]
```css
 a {
transition: #1fb2b0 0.1s linear;
-webkit-transition: 0.1s;
-moz-transition: 0.1s;
-o-transition: 0.1s;
}

a:hover {
    color: #1fb2b0;
}
```

So, du Nasenbär. Keine Ahnung was da bei dir genau gleich aussieht, aber beim hovern solltest du wohl bemerkt haben, dass sich die Farbe der Links nicht schlagartig ändert. Probeweiser kannst du ja mal die Sekundenzahl auf 2 oder so erhöhen und schauen, was passiert.
Ansonsten soll google helfen, da kannst ja auch mal lesen, was das tut.
